name: Build and Publish Workflow
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com/"
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
